INFO 2021-01-02 12:04:25,916 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-06 11:01:11,364 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-06 11:09:05,912 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-06 11:10:34,535 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-06 11:21:01,665 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-19 09:59:38,011 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-19 10:05:39,875 autoreload 597 Watching for file changes with StatReloader
WARNING 2021-01-19 10:07:58,952 log 222 Not Found: /
WARNING 2021-01-19 10:07:58,954 basehttp 154 "GET / HTTP/1.1" 404 2579
WARNING 2021-01-19 10:07:59,041 log 222 Not Found: /favicon.ico
WARNING 2021-01-19 10:07:59,042 basehttp 154 "GET /favicon.ico HTTP/1.1" 404 2630
INFO 2021-01-19 10:11:35,475 autoreload 597 Watching for file changes with StatReloader
WARNING 2021-01-19 10:11:38,890 log 222 Not Found: /
WARNING 2021-01-19 10:11:38,891 basehttp 154 "GET / HTTP/1.1" 404 2579
INFO 2021-01-19 10:13:59,092 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-19 10:20:37,417 autoreload 597 Watching for file changes with StatReloader
WARNING 2021-01-19 10:21:13,555 log 222 Not Found: /
WARNING 2021-01-19 10:21:13,556 basehttp 154 "GET / HTTP/1.1" 404 2579
WARNING 2021-01-19 10:21:13,759 log 222 Not Found: /favicon.ico
WARNING 2021-01-19 10:21:13,762 basehttp 154 "GET /favicon.ico HTTP/1.1" 404 2630
INFO 2021-01-19 10:33:17,102 autoreload 597 Watching for file changes with StatReloader
WARNING 2021-01-19 10:33:23,495 log 222 Not Found: /
WARNING 2021-01-19 10:33:23,502 basehttp 154 "GET / HTTP/1.1" 404 2579
WARNING 2021-01-19 10:33:23,796 log 222 Not Found: /favicon.ico
WARNING 2021-01-19 10:33:23,798 basehttp 154 "GET /favicon.ico HTTP/1.1" 404 2630
INFO 2021-01-19 10:37:18,718 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-19 10:39:16,103 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-19 10:39:26,493 basehttp 154 "GET /api/v1.0/session HTTP/1.1" 200 47
WARNING 2021-01-19 10:39:26,627 log 222 Not Found: /api/v1.0/houses/index
WARNING 2021-01-19 10:39:26,630 log 222 Not Found: /api/v1.0/areas
WARNING 2021-01-19 10:39:26,631 basehttp 154 "GET /api/v1.0/houses/index HTTP/1.1" 404 2665
WARNING 2021-01-19 10:39:26,633 basehttp 154 "GET /api/v1.0/areas HTTP/1.1" 404 2644
INFO 2021-01-19 10:39:30,990 basehttp 154 "GET /api/v1.0/imagecode?cur=435253df-9945-4658-9e16-c8252a5008bd&pre= HTTP/1.1" 301 0
ERROR 2021-01-19 10:39:33,704 log 222 Internal Server Error: /api/v1.0/imagecode/
Traceback (most recent call last):
  File "F:\biShe\venv\lib\site-packages\redis\connection.py", line 559, in connect
    sock = self._connect()
  File "F:\biShe\venv\lib\site-packages\redis\connection.py", line 615, in _connect
    raise err
  File "F:\biShe\venv\lib\site-packages\redis\connection.py", line 603, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\biShe\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "F:\biShe\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\biShe\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "F:\biShe\venv\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "F:\biShe\venv\lib\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "F:\biShe\zuFang\zuFang\apps\users\views.py", line 37, in get
    redis_conn.setex('img_%s' % cur, 300, text)
  File "F:\biShe\venv\lib\site-packages\redis\client.py", line 1822, in setex
    return self.execute_command('SETEX', name, time, value)
  File "F:\biShe\venv\lib\site-packages\redis\client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "F:\biShe\venv\lib\site-packages\redis\connection.py", line 1192, in get_connection
    connection.connect()
  File "F:\biShe\venv\lib\site-packages\redis\connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10061 connecting to 127.0.0.1:6379. 由于目标计算机积极拒绝，无法连接。.
ERROR 2021-01-19 10:39:33,714 basehttp 154 "GET /api/v1.0/imagecode/?cur=435253df-9945-4658-9e16-c8252a5008bd&pre= HTTP/1.1" 500 115625
INFO 2021-01-19 10:39:36,243 basehttp 154 "GET /api/v1.0/imagecode?cur=ee7b99d8-d267-41b8-b496-bb296c35532d&pre=435253df-9945-4658-9e16-c8252a5008bd HTTP/1.1" 301 0
ERROR 2021-01-19 10:39:38,333 log 222 Internal Server Error: /api/v1.0/imagecode/
Traceback (most recent call last):
  File "F:\biShe\venv\lib\site-packages\redis\connection.py", line 559, in connect
    sock = self._connect()
  File "F:\biShe\venv\lib\site-packages\redis\connection.py", line 615, in _connect
    raise err
  File "F:\biShe\venv\lib\site-packages\redis\connection.py", line 603, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\biShe\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "F:\biShe\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "F:\biShe\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "F:\biShe\venv\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "F:\biShe\venv\lib\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "F:\biShe\zuFang\zuFang\apps\users\views.py", line 33, in get
    redis_conn.delete('img_%s' % pre)
  File "F:\biShe\venv\lib\site-packages\redis\client.py", line 1567, in delete
    return self.execute_command('DEL', *names)
  File "F:\biShe\venv\lib\site-packages\redis\client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "F:\biShe\venv\lib\site-packages\redis\connection.py", line 1192, in get_connection
    connection.connect()
  File "F:\biShe\venv\lib\site-packages\redis\connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10061 connecting to 127.0.0.1:6379. 由于目标计算机积极拒绝，无法连接。.
ERROR 2021-01-19 10:39:38,349 basehttp 154 "GET /api/v1.0/imagecode/?cur=ee7b99d8-d267-41b8-b496-bb296c35532d&pre=435253df-9945-4658-9e16-c8252a5008bd HTTP/1.1" 500 115645
INFO 2021-01-19 15:35:02,533 autoreload 597 Watching for file changes with StatReloader
INFO 2021-01-19 15:35:31,477 basehttp 154 "GET /api/v1.0/session HTTP/1.1" 200 47
WARNING 2021-01-19 15:35:31,592 log 222 Not Found: /api/v1.0/houses/index
WARNING 2021-01-19 15:35:31,593 log 222 Not Found: /api/v1.0/areas
WARNING 2021-01-19 15:35:31,594 basehttp 154 "GET /api/v1.0/houses/index HTTP/1.1" 404 2665
WARNING 2021-01-19 15:35:31,594 basehttp 154 "GET /api/v1.0/areas HTTP/1.1" 404 2644
INFO 2021-01-19 15:35:33,321 basehttp 154 "GET /api/v1.0/imagecode?cur=65352919-fc32-45bc-8183-20508d210230&pre= HTTP/1.1" 301 0
INFO 2021-01-19 15:35:33,597 basehttp 154 "GET /api/v1.0/imagecode/?cur=65352919-fc32-45bc-8183-20508d210230&pre= HTTP/1.1" 200 3035
INFO 2021-01-19 15:35:51,768 basehttp 154 "OPTIONS /api/v1.0/sms/ HTTP/1.1" 200 0
INFO 2021-01-19 15:35:51,827 views 126 974230
INFO 2021-01-19 15:35:51,835 basehttp 154 "POST /api/v1.0/sms/ HTTP/1.1" 200 50
INFO 2021-01-19 15:36:19,822 basehttp 154 "OPTIONS /api/v1.0/users HTTP/1.1" 200 0
INFO 2021-01-19 15:36:20,510 basehttp 154 "POST /api/v1.0/users HTTP/1.1" 200 52
WARNING 2021-01-19 15:36:21,101 log 222 Not Found: /api/v1.0/houses/index
WARNING 2021-01-19 15:36:21,103 log 222 Not Found: /api/v1.0/areas
INFO 2021-01-19 15:36:21,103 basehttp 154 "GET /api/v1.0/session HTTP/1.1" 200 93
WARNING 2021-01-19 15:36:21,105 basehttp 154 "GET /api/v1.0/houses/index HTTP/1.1" 404 2665
WARNING 2021-01-19 15:36:21,105 basehttp 154 "GET /api/v1.0/areas HTTP/1.1" 404 2644
WARNING 2021-01-19 15:36:25,248 log 222 Not Found: /api/v1.0/user
WARNING 2021-01-19 15:36:25,249 basehttp 154 "GET /api/v1.0/user HTTP/1.1" 404 2641
WARNING 2021-01-19 15:36:28,914 log 222 Not Found: /api/v1.0/orders
WARNING 2021-01-19 15:36:28,920 basehttp 154 "GET /api/v1.0/orders?role=custom HTTP/1.1" 404 2659
WARNING 2021-01-19 15:36:31,040 log 222 Not Found: /api/v1.0/user
WARNING 2021-01-19 15:36:31,041 basehttp 154 "GET /api/v1.0/user HTTP/1.1" 404 2641
WARNING 2021-01-19 15:36:32,632 log 222 Not Found: /api/v1.0/user/auth
WARNING 2021-01-19 15:36:32,633 basehttp 154 "GET /api/v1.0/user/auth HTTP/1.1" 404 2656
WARNING 2021-01-19 15:36:35,352 log 222 Not Found: /api/v1.0/user
WARNING 2021-01-19 15:36:35,353 basehttp 154 "GET /api/v1.0/user HTTP/1.1" 404 2641
WARNING 2021-01-19 15:36:37,347 log 222 Not Found: /api/v1.0/user/auth
WARNING 2021-01-19 15:36:37,348 basehttp 154 "GET /api/v1.0/user/auth HTTP/1.1" 404 2656
WARNING 2021-01-19 15:36:39,351 log 222 Not Found: /api/v1.0/user
WARNING 2021-01-19 15:36:39,351 basehttp 154 "GET /api/v1.0/user HTTP/1.1" 404 2641
INFO 2021-01-19 15:36:41,190 basehttp 154 "OPTIONS /api/v1.0/session HTTP/1.1" 200 0
INFO 2021-01-19 15:36:41,205 basehttp 154 "DELETE /api/v1.0/session HTTP/1.1" 200 46
INFO 2021-01-19 15:36:41,276 basehttp 154 "GET /api/v1.0/session HTTP/1.1" 200 47
WARNING 2021-01-19 15:36:41,285 log 222 Not Found: /api/v1.0/houses/index
WARNING 2021-01-19 15:36:41,285 log 222 Not Found: /api/v1.0/areas
WARNING 2021-01-19 15:36:41,292 basehttp 154 "GET /api/v1.0/areas HTTP/1.1" 404 2644
WARNING 2021-01-19 15:36:41,292 basehttp 154 "GET /api/v1.0/houses/index HTTP/1.1" 404 2665
INFO 2021-01-19 15:36:56,614 basehttp 154 "POST /api/v1.0/session HTTP/1.1" 200 52
INFO 2021-01-19 15:36:56,701 basehttp 154 "GET /api/v1.0/session HTTP/1.1" 200 93
WARNING 2021-01-19 15:36:56,704 log 222 Not Found: /api/v1.0/houses/index
WARNING 2021-01-19 15:36:56,706 log 222 Not Found: /api/v1.0/areas
WARNING 2021-01-19 15:36:56,707 basehttp 154 "GET /api/v1.0/houses/index HTTP/1.1" 404 2665
WARNING 2021-01-19 15:36:56,708 basehttp 154 "GET /api/v1.0/areas HTTP/1.1" 404 2644
